parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Scheduler\Infrastructure\Controller\ScheduleController:
        arguments:
            $facade: '@App\Scheduler\Application\SchedulerFacade'

    App\Scheduler\Domain\SchedulerFacadeImpl:
        arguments: []

    App\Scheduler\Application\SchedulerFacade:
        alias: App\Scheduler\Domain\SchedulerFacadeImpl
    App\Scheduler\Infrastructure\Messages\SchedulerGenerateMessageHandler:
        arguments:
            $facade: '@App\Scheduler\Application\SchedulerFacade'
        tags:
            - { name: 'messenger.message_handler', bus: 'scheduler_bus' }