nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: '@cors_allow_origin_array'
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': ~
