nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin:
            - 'http://localhost'
            - 'http://127.0.0.1'
            - 'http://frontend.scheduler'
            - 'http://call-center.pythdev.pl'
            - 'http://api-call-center.pythdev.pl'
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': ~
